import { Subject, Level } from './types';

export type Status = 'Not Started' | 'In Progress' | 'Mastered';

export interface Topic {
  id: string;
  name: string;
  form: 1 | 2 | 3 | 4;
}

export type SyllabusData = {
  [key in Subject]: Topic[];
};

export const syllabusData: SyllabusData = {
  Mathematics: [
    { id: 'm101', name: 'Natural Numbers', form: 1 },
    { id: 'm102', name: 'Factors', form: 1 },
    { id: 'm103', name: 'Divisibility Tests', form: 1 },
    { id: 'm104', name: 'GCD and LCM', form: 1 },
    { id: 'm105', name: 'Integers', form: 1 },
    { id: 'm106', name: 'Fractions', form: 1 },
    { id: 'm107', name: 'Decimals', form: 1 },
    { id: 'm108', name: 'Squares and Square Roots', form: 1 },
    { id: 'm109', name: 'Algebraic Expressions', form: 1 },
    { id: 'm110', name: 'Rates, Ratio, Proportion and Percentages', form: 1 },
    { id: 'm111', name: 'Linear Equations', form: 1 },
    { id: 'm112', name: 'Commercial Arithmetic 1', form: 1 },
    { id: 'm201', name: 'Cubes and Cube Roots', form: 2 },
    { id: 'm202', name: 'Reciprocals', form: 2 },
    { id: 'm203', name: 'Indices and Logarithms', form: 2 },
    { id: 'm204', name: 'Equations of Straight Lines', form: 2 },
    { id: 'm205', name: 'Reflection and Congruence', form: 2 },
    { id: 'm206', name: 'Rotation', form: 2 },
    { id: 'm207', name: 'Similarity and Enlargement', form: 2 },
    { id: 'm208', name: 'Pythagoras Theorem', form: 2 },
    { id: 'm209', name: 'Trigonometry 1', form: 2 },
    { id: 'm210', name: 'Area of Triangle and Quadrilaterals', form: 2 },
    { id: 'm211', name: 'Equations and Curves', form: 2 },
    { id: 'm301', name: 'Quadratic Expressions and Equations 2', form: 3 },
    { id: 'm302', name: 'Approximation and Error', form: 3 },
    { id: 'm303', name: 'Trigonometry 2', form: 3 },
    { id: 'm304', name: 'Surds', form: 3 },
    { id: 'm305', name: 'Logarithms 2', form: 3 },
    { id: 'm306', name: 'Commercial Arithmetic 2', form: 3 },
    { id: 'm307', name: 'Circles, Chords and Tangents', form: 3 },
    { id: 'm308', name: 'Matrices', form: 3 },
    { id: 'm309', name: 'Formulae and Variations', form: 3 },
    { id: 'm310', name: 'Sequences and Series', form: 3 },
    { id: 'm311', name: 'Vectors 2', form: 3 },
    { id: 'm312', name: 'Binomial Expansion', form: 3 },
    { id: 'm313', name: 'Probability', form: 3 },
    { id: 'm314', name: 'Compound Proportions and Mixtures', form: 3 },
    { id: 'm315', name: 'Graphical Methods', form: 3 },
    { id: 'm401', name: 'Matrices and Transformations', form: 4 },
    { id: 'm402', name: 'Statistics 2', form: 4 },
    { id: 'm403', name: 'Loci', form: 4 },
    { id: 'm404', name: 'Trigonometry 3', form: 4 },
    { id: 'm405', name: 'Three Dimensional Geometry', form: 4 },
    { id: 'm406', name: 'Longitudes and Latitudes', form: 4 },
    { id: 'm407', name: 'Linear Programming', form: 4 },
    { id: 'm408', name: 'Differentiation', form: 4 },
    { id: 'm409', name: 'Integration', form: 4 },
  ],
  Physics: [
    { id: 'p101', name: 'Introduction to Physics', form: 1 },
    { id: 'p102', name: 'Measurements 1', form: 1 },
    { id: 'p103', name: 'Force', form: 1 },
    { id: 'p104', name: 'Pressure', form: 1 },
    { id: 'p105', name: 'Particulate Nature of Matter', form: 1 },
    { id: 'p106', name: 'Thermal Expansion', form: 1 },
    { id: 'p107', name: 'Heat Transfer', form: 1 },
    { id: 'p108', name: 'Rectilinear Propagation of Light', form: 1 },
    { id: 'p109', name: 'Electrostatics 1', form: 1 },
    { id: 'p110', name: 'Cells and Simple Circuits', form: 1 },
    { id: 'p201', name: 'Magnetism', form: 2 },
    { id: 'p202', name: 'Measurements 2', form: 2 },
    { id: 'p203', name: 'Turning Effect of Force', form: 2 },
    { id: 'p204', name: 'Equilibrium and Center of Gravity', form: 2 },
    { id: 'p205', name: 'Reflection at Curved Surfaces', form: 2 },
    { id: 'p206', name: 'Magnetic Effect of Electric Current', form: 2 },
    { id: 'p207', name: 'Hooke\'s Law', form: 2 },
    { id: 'p208', name: 'Waves 1', form: 2 },
    { id: 'p209', name: 'Sound', form: 2 },
    { id: 'p210', name: 'Fluid Flow', form: 2 },
    { id: 'p301', name: 'Linear Motion', form: 3 },
    { id: 'p302', name: 'Refraction of Light', form: 3 },
    { id: 'p303', name: 'Newton\'s Laws of Motion', form: 3 },
    { id: 'p304', name: 'Work, Energy, Power and Machines', form: 3 },
    { id: 'p305', name: 'Current Electricity 2', form: 3 },
    { id: 'p306', name: 'Waves 2', form: 3 },
    { id: 'p307', name: 'Electrostatics 2', form: 3 },
    { id: 'p308', name: 'Heating Effect of Electric Current', form: 3 },
    { id: 'p309', name: 'Quantity of Heat', form: 3 },
    { id: 'p310', name: 'Gas Laws', form: 3 },
    { id: 'p401', name: 'Thin Lenses', form: 4 },
    { id: 'p402', name: 'Uniform Circular Motion', form: 4 },
    { id: 'p403', name: 'Floating and Sinking', form: 4 },
    { id: 'p404', name: 'Electromagnetic Spectrum', form: 4 },
    { id: 'p405', name: 'Electromagnetic Induction', form: 4 },
    { id: 'p406', name: 'Mains Electricity', form: 4 },
    { id: 'p407', name: 'Cathode Rays and Cathode Ray Tube', form: 4 },
    { id: 'p408', name: 'X-Rays', form: 4 },
    { id: 'p409', name: 'Photoelectric Effect', form: 4 },
    { id: 'p410', name: 'Radioactivity', form: 4 },
    { id: 'p411', name: 'Electronics', form: 4 },
  ],
  Chemistry: [
    { id: 'c101', name: 'Introduction to Chemistry', form: 1 },
    { id: 'c102', name: 'Classification of Substances', form: 1 },
    { id: 'c103', name: 'Acids, Bases and Indicators', form: 1 },
    { id: 'c104', name: 'Air and Combustion', form: 1 },
    { id: 'c105', name: 'Water and Hydrogen', form: 1 },
    { id: 'c201', name: 'Structure of Atom and Period Table', form: 2 },
    { id: 'c202', name: 'Chemical Families', form: 2 },
    { id: 'c203', name: 'Structure and Bonding', form: 2 },
    { id: 'c204', name: 'Salts', form: 2 },
    { id: 'c205', name: 'Effect of Electric Current on Substances', form: 2 },
    { id: 'c206', name: 'Carbon and its Compounds', form: 2 },
    { id: 'c301', name: 'Gas Laws', form: 3 },
    { id: 'c302', name: 'Mole Concept', form: 3 },
    { id: 'c303', name: 'Organic Chemistry 1', form: 3 },
    { id: 'c304', name: 'Nitrogen and its Compounds', form: 3 },
    { id: 'c305', name: 'Sulphur and its Compounds', form: 3 },
    { id: 'c306', name: 'Chlorine and its Compounds', form: 3 },
    { id: 'c401', name: 'Acids, Bases and Salts 2', form: 4 },
    { id: 'c402', name: 'Energy Changes in Physical and Chemical Processes', form: 4 },
    { id: 'c403', name: 'Reaction Rates and Reversible Reactions', form: 4 },
    { id: 'c404', name: 'Electrochemistry', form: 4 },
    { id: 'c405', name: 'Metals', form: 4 },
    { id: 'c406', name: 'Organic Chemistry 2', form: 4 },
    { id: 'c407', name: 'Radioactivity', form: 4 },
  ],
  Biology: [
    { id: 'b101', name: 'Introduction to Biology', form: 1 },
    { id: 'b102', name: 'Classification 1', form: 1 },
    { id: 'b103', name: 'The Cell', form: 1 },
    { id: 'b104', name: 'Cell Physiology', form: 1 },
    { id: 'b105', name: 'Nutrition in Plants and Animals', form: 1 },
    { id: 'b201', name: 'Transport in Plants and Animals', form: 2 },
    { id: 'b202', name: 'Gaseous Exchange', form: 2 },
    { id: 'b203', name: 'Respiration', form: 2 },
    { id: 'b204', name: 'Excretion and Homeostasis', form: 2 },
    { id: 'b301', name: 'Classification 2', form: 3 },
    { id: 'b302', name: 'Ecology', form: 3 },
    { id: 'b303', name: 'Reproduction in Plants and Animals', form: 3 },
    { id: 'b304', name: 'Growth and Development', form: 3 },
    { id: 'b401', name: 'Genetics', form: 4 },
    { id: 'b402', name: 'Evolution', form: 4 },
    { id: 'b403', name: 'Reception, Response and Coordination in Plants and Animals', form: 4 },
    { id: 'b404', name: 'Support and Movement in Plants and Animals', form: 4 },
  ],
  'Computer Science': [
    { id: 'cs101', name: 'Introduction to Computers', form: 1 },
    { id: 'cs102', name: 'Computer Systems', form: 1 },
    { id: 'cs103', name: 'Operating Systems', form: 1 },
    { id: 'cs201', name: 'Word Processing', form: 2 },
    { id: 'cs202', name: 'Spreadsheets', form: 2 },
    { id: 'cs203', name: 'Databases', form: 2 },
    { id: 'cs204', name: 'Desktop Publishing', form: 2 },
    { id: 'cs205', name: 'Internet and E-mail', form: 2 },
    { id: 'cs206', name: 'Data Security and Controls', form: 2 },
    { id: 'cs301', name: 'Data Representation in a Computer', form: 3 },
    { id: 'cs302', name: 'Data Processing', form: 3 },
    { id: 'cs303', name: 'Elementary Programming Principles', form: 3 },
    { id: 'cs304', name: 'Systems Development', form: 3 },
    { id: 'cs401', name: 'Networking and Data Communication', form: 4 },
    { id: 'cs402', name: 'Application Areas of ICT', form: 4 },
    { id: 'cs403', name: 'Impact of ICT on Society', form: 4 },
    { id: 'cs404', name: 'Career Opportunities in ICT', form: 4 },
  ],
};
